### ISSUE TITLE
[2.1.0] client crash on startup

### ISSUE THREAD

**Issue by kreezxil** [janagyjr/tcgs-chillpack#5]
client crash report: http://paste.ubuntu.com/p/wfJH5tDyrY/

If allocated another 4gb from the default GDLauncher of 4gb doesn't resolve the issue, then there exists an issue with Extra Utilities, that except for their piping system, compressed stones, and wither proof glass is one of the worst mods in existence.

**Comment by kreezxil** [comment]
Saw that you said on GDLauncher Discord

```discord
[8:11 AM] TCGJoe: It's the same crash I'm having. 6/7 on the second pass of some texture reload. I have 8GB allocated, fwiw.
[8:11 AM] TCGJoe: Thanks, I made it in The GIMP.
```
That being the case if I crash again, I'll remove extra utilities and see what happens.

**Comment by kreezxil** [comment]
ok, it crashed at the exact same spot with 8GB of ram.

I'm removing EU from the pack now to see if we can actually launch without it.

**Comment by kreezxil** [comment]
removing Extra Utilities allowed your pack to launch in GDLauncher.

![image](https://user-images.githubusercontent.com/3880072/69814021-017fdc00-11b9-11ea-9f1c-79c8605ae0ec.png)

It should be noted that crash reports mean what they say, if they say a mod is reliably causing your crash, then that mod is the culprit. Not the launcher.

**Comment by kreezxil** [comment]
Also, I suspect your CUSTOM MAIN MENU is not setup right, this looks like the AETHER II screen. This can negatively effect your popularity because it'll look like you're ripping off another pack.

**Comment by janagyjr** [comment]
Thanks, I'll look to see what EU2 can be replaced with. I wanted it for the Angel Ring but by the time I get close enough in this version, I have better flight from other mods. 

I'm going to leave this open for a bit.

**Comment by kreezxil** [comment]
further testing reveals that your pack will not run in one way or the other on Twitch. I suspect it has something to do with the recent Twitch updates. 

I think for your pack listing you will need to say what launchers it runs on and which it does not. probably put a link at the top called "launcher compatibility" that jumps to an anchor label at the bottom of the overview that lists them.

**Comment by janagyjr** [comment]
I'm actually playing via Twitch launcher (jar option) rn, but that's not a bad idea. Used to be Twitch was the only launcher I endorsed.

**Comment by janagyjr** [comment]
Aether menu issue fixed (config setting in Aether mod lets you use it's own menu system or not) in upcoming update (config and mod version update). 

Extra Utilities 2 will be removed if I can find a replacement setup for autocrafting pure AE2 crystals (currently use EU2 pipes and nodes with world interaction upgrades to suck up nearby crystals (with appropriate filters). 

Closing this bug once I provide on the project page on Curse sufficient warning about using specific launchers I am aware of. Thank you for the massive help you've been in tracking this issue down. Will be reporting the bug to EU2 dev to unknown reception.

**Comment by janagyjr** [comment]
Warning is posted in pack description, closing the issue here and will be submitting your pastebin and my own gist'd crash report from GDLauncher once pack is updated.
